name: Dotnet3 Scan

on:
  push:
    branches: [ main ]
    paths:
      - "3/**"
  pull_request:
    types: [closed]
    branches: [ main ]
    paths:
      - "3/**"


jobs:

  name:
    uses: Vuzee01/workflow/.github/workflows/GetOrgName.yml@main

  print_test:
    name: test
    runs-on: ubuntu-latest
    needs: name
    steps:
      - name: print output
        run: echo ${{ needs.job1.outputs.firstword }} ${{ needs.job1.outputs.secondword }}

  # build:
  #   uses: Vuzee01/workflow/.github/workflows/SonarQubeDotnet.yml@main
  #   with:
  #     project_name: "Vuzee01_${{ github.event.repository.name }}"
  #     build_dir: "3/"
  #     org_name: "${{ steps.get_org_name.outputs.ORG_NAME }}"
  #   secrets:
  #     sonar_token: ${{ secrets.SONAR_TOKEN }}
  #     github_token: ${{ secrets.GITHUB_TOKEN }}
