name: Dotnet3 Scan

on:
  push:
    branches: [ main ]
    paths:
      - "3/**"
  pull_request:
    types: [ opened, synchronize, closed ]
    branches: [ main, master ]
    paths:
      - "3/**"


jobs:

  deploy:
    name: Deploy App
    runs-on: ubuntu-latest
    steps:
      - name: Get env data
        id: env_data1
        uses: ${{github.action_path}}../../resolver/
        with:
          app_env: "newenv"
          app_name: "service2"
          docker_repo_host: "eu.gcr.io"
      - name: print env
        run: |
          echo service_name ${{ steps.env_data1.outputs.app_service }}
          echo cluser name ${{ steps.env_data1.outputs.cluster }}
          echo WFS ${{ steps.env_data1.outputs.wait_for_service }}
          echo repo ${{ steps.env_data1.outputs.repo }}
          echo acc id ${{ steps.env_data1.outputs.aws_acc_id }}
          echo taskdef loc ${{ steps.env_data1.outputs.taskdef }}


  # name:
  #   uses: Vuzee01/workflow/.github/workflows/GetOrgName.yml@main

  # print_test:
  #   name: test
  #   runs-on: ubuntu-latest
  #   needs: name
  #   steps:
  #     - name: print output
  #       run: echo ${{ needs.name.outputs.ORG_NAME }}
  #     - id: test-pr
  #       uses: htec-infra/gha-utils/actions/comment-pr@v0.1.0
  #       with:
  #         github_token: "${{ secrets.GITHUB_TOKEN }}"
  #     - id: test-pr2
  #       uses: htec-infra/gha-utils/actions/comment-pr@v0.1.0
  #       with:
  #         github_token: "${{ secrets.GITHUB_TOKEN }}"
  #     - id: test-pr3
  #       uses: htec-infra/gha-utils/actions/comment-pr@v0.1.0
  #       with:
  #         github_token: "${{ secrets.GITHUB_TOKEN }}"
  # test_comment:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - id: test-pr
  #       uses: htec-infra/gha-utils/utils/comment-pr@improvement/expand-workflows
  #       with:
  #         token: "${{ secrets.GITHUB_TOKEN }}"

