name: Dotnet3 Scan

on:
  push:
    branches: [ main ]
    paths:
      - "3/**"
  pull_request:
    types: [closed]
    branches: [ main ]
    paths:
      - "3/**"


jobs:
  build:
    uses: Vuzee01/workflow/.github/workflows/SonarQubeDotnet.yml@main
    with:
      dotnet_version: "6.0.x"
      project_name: "Vuzee01_dotnet"
      org_name: "vuzimir"
      build_dir: "3/"
    secrets:
      sonar_token: ${{ secrets.SONAR_TOKEN }}
      github_token: ${{ secrets.GITHUB_TOKEN }}