name: Dotnet3 Scan

on: push


jobs:

  sonarcloud:
    name: Code Quality check
    uses: htec-infra/gha-tbd/.github/workflows/sonarscan-dotnet.yml@main
    with:
      build_dir: "src/"
    secrets:
      sonar_token: ${{ secrets.SONAR_TOKEN }}
      gh_token: ${{ secrets.GITHUB_TOKEN }}
  # name:
  #   uses: Vuzee01/workflow/.github/workflows/GetOrgName.yml@main

  # print_test:
  #   name: test
  #   runs-on: ubuntu-latest
  #   needs: name
  #   steps:
  #     - name: print output
  #       run: echo ${{ needs.name.outputs.ORG_NAME }}
  #     - id: test-pr
  #       uses: htec-infra/gha-utils/actions/comment-pr@v0.1.0
  #       with:
  #         github_token: "${{ secrets.GITHUB_TOKEN }}"
  #     - id: test-pr2
  #       uses: htec-infra/gha-utils/actions/comment-pr@v0.1.0
  #       with:
  #         github_token: "${{ secrets.GITHUB_TOKEN }}"
  #     - id: test-pr3
  #       uses: htec-infra/gha-utils/actions/comment-pr@v0.1.0
  #       with:
  #         github_token: "${{ secrets.GITHUB_TOKEN }}"
  # test_comment:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - id: test-pr
  #       uses: htec-infra/gha-utils/utils/comment-pr@improvement/expand-workflows
  #       with:
  #         token: "${{ secrets.GITHUB_TOKEN }}"

