name: Deploy App on ECS (v2)

on:
  # manual trigger
  workflow_dispatch:
    inputs:
      name:
        description: 'Application Name'
        required: true
      env:
        description: 'Environment'
        required: false
      version:
        description: 'Version (docker tag)'
        required: true
      tenant:
        description: 'Tenant'
        required: false
  
  repository_dispatch:
    types: [ app_deploy_v2 ]


jobs:
  deploy:
    name: Deploy ECS Service
    runs-on: ubuntu-latest
    steps:
      - name: check status
        id: checksecrets
        run: |
          if [ "$inputs.tenant" == "" ]; then
            echo ::set-output name=secretspresent::false
          else
            echo ::set-output name=secretspresent::true
          fi
      - name: env
        if: ${{ inputs.env }}
        run: |
           echo "Ide za env"
      - name: tenant
        if: ${{ steps.checksecrets.outputs.secretspresent }}
        run: |
           echo "Ide za tenant"
