name: Deploy App on ECS (v2)

on:
  # manual trigger
  workflow_dispatch:
    inputs:
      name:
        description: 'Application Name'
        required: true
      env:
        description: 'Environment'
        required: false
      version:
        description: 'Version (docker tag)'
        required: true
      tenant:
        description: 'Tenant'
        required: false
  
  repository_dispatch:
    types: [ app_deploy_v2 ]

env:
  APP_ENV: ${{ inputs.env  }}
  APP_TENANT: ${{ github.event.client_payload.tenant }}

jobs:
  deploy:
    name: Deploy ECS Service
    runs-on: ubuntu-latest
    steps:
      - name: check status
        id: checksecrets
        run: |
          echo "${APP_TENANT}"
          echo "${APP_ENV}"
          if [[ -z "${APP_TENANT}" ]]; then
            echo ::set-output name=tenant::false
          else
            echo ::set-output name=tenant::true
          fi
          
          if [[ -z "${APP_ENV}" ]]; then
            echo ::set-output name=env::false
          else
            echo ::set-output name=env::true
          fi
      - name: Tenant
        if: ${{ env.APP_TENANT }}
        run: |
           echo "Ide za tenant"
      - name: Env
        if: ${{ env.APP_ENV }}
        run: |
           echo "Ide za env"
